apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: pubsub-sample@pubsub-sample-1234.iam.gserviceaccount.com
  labels:
    app: pubsub-sample
    cluster: cluster-west
    owner: pubsub-sample-team
  name: pubsub-sample
  namespace: pubsub-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-sample
    cluster: cluster-west
    owner: pubsub-sample-team
  name: pubsub-sample
  namespace: pubsub-sample
spec:
  selector:
    matchLabels:
      app: pubsub-sample
      cluster: cluster-west
      owner: pubsub-sample-team
  template:
    metadata:
      labels:
        app: pubsub-sample
        cluster: cluster-west
        owner: pubsub-sample-team
    spec:
      containers:
      - image: gcr.io/google-samples/pubsub-sample:v1
        name: subscriber
      serviceAccountName: pubsub-sample
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: pubsub-sample
    cluster: cluster-west
    owner: pubsub-sample-team
  name: pubsub-sample
  namespace: pubsub-sample
spec:
  maxReplicas: 5
  metrics:
  - external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: echo-read
      target:
        averageValue: 2
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pubsub-sample
