apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: cluster-west
    owner: platform-team
  name: default
  namespace: tenant-a
spec:
  hard:
    cpu: "100"
    memory: 10Gi
    pods: "10"
