apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster: cluster-west
    owner: platform-team
  name: namespace-viewer
  namespace: tenant-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-c1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-c2
