apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../all-clusters/all-namespaces/
- ../../../../all-clusters/namespaces/tenant-a/
patchesStrategicMerge:
- resource-quota.yaml
commonLabels:
  cluster: cluster-east
namespace: tenant-a