apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoneprinter
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/zone-printer:0.2
        ports:
        - containerPort: 8080
