apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-sample
spec:
  template:
    spec:
      containers:
      - name: subscriber
        image: gcr.io/google-samples/pubsub-sample:v1
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "${PUBSUB_SAMPLE_PROJECT_ID}"
      serviceAccountName: pubsub-sample
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pubsub-sample
  annotations:
    iam.gke.io/gcp-service-account: pubsub-sample@${PLATFORM_PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub-sample
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - external:
      metric:
       name: pubsub.googleapis.com|subscription|num_undelivered_messages
       selector:
         matchLabels:
           resource.labels.subscription_id: echo-read
           resource.labels.project_id: "${PUBSUB_SAMPLE_PROJECT_ID}"
      target:
        type: AverageValue
        averageValue: 2
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pubsub-sample
