apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: default
  namespace: tenant-c
spec:
  hard:
    cpu: "100"
    memory: 10Gi
    pods: "10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: namespace-viewer
  namespace: tenant-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-21
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-22
