apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: default
  namespace: tenant-a
spec:
  hard:
    cpu: "1000"
    memory: 100Gi
    pods: "100"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: namespace-viewer
  namespace: tenant-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-2
