apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: default
  namespace: tenant-a
spec:
  hard:
    cpu: "1000"
    memory: 100Gi
    pods: "100"
